### PR TITLE
Update Tabos Roger and runtime version

### PR DESCRIPTION
**Pull request by yakushabb**
- Update Tabos Roger version to 2.4.90
- Update librm version to 2.3.4
- Update runtime to 46
- Fix appdata related issues

### CODE REVIEW

**Comment by ghost** [comment]
@janbrummer I've updated Tabos Roger runtime to 46 and Tabos Roger version to 2.4.90. 

Also fixed some appdata issues.

**Comment by janbrummer** [comment]
> @janbrummer I've updated Tabos Roger runtime to 46 and Tabos Roger version to 2.4.90.
> 
> Also fixed some appdata issues.

Thanks!!

**Comment by ghost** [comment]
@barthalion I've updated Tabos Roger runtime to 46 and Tabos Roger version to 2.4.90.

**Comment by ghost** [comment]
Sent to upstream: https://gitlab.com/tabos/rogerrouter/-/merge_requests/40

**Pull request merged**
