### PR TITLE
bumping runtime to 45

### PR DESCRIPTION
**Pull request by muelli**
let's see whether this builds

### CODE REVIEW

**Comment by muelli** [comment]
```
{
    "warnings": [
        "module-evolution-data-server-buildsystem-is-plain-cmake",
        "finish-args-contains-both-x11-and-wayland",
        "module-libical-buildsystem-is-plain-cmake"
    ]
}
```

**Comment by janbrummer** [comment]
Doesn't look like a problem of my code, right?

**Comment by muelli** [comment]
well, rather the manifest. https://github.com/flathub/org.tabos.roger/blob/45bc86e538c3974b20e9ababd581f0aab0fa28bb/org.tabos.roger.json#L8 should probably be "fallback-x11".

And I *guess* that it's happier with https://github.com/flathub/org.tabos.roger/blob/45bc86e538c3974b20e9ababd581f0aab0fa28bb/org.tabos.roger.json#L152 being cmake-ninja.

**Comment by janbrummer** [comment]
Ahhh, i got it. Thanks for clarification. Could you prepare a PR?

**Comment by muelli** [comment]
don't hold your breath.

**Comment by muelli** [comment]
https://github.com/flathub/org.tabos.roger/pull/12

**Comment by muelli** [comment]
```
dependency gobject-2.0 found: YES 2.78.1
Run-time dependency gio-2.0 found: YES 2.78.1
Found CMake: /usr/bin/cmake (3.27.9)
Run-time dependency libsoup-2.4 found: NO (tried pkgconfig and cmake)
../meson.build:68:4: ERROR: Dependency "libsoup-2.4" not found, tried pkgconfig and cmake
```

**Comment by janbrummer** [comment]
I'm sorry, i forgot this one :( My bad. Updated in another PR, so closing. Thanks for your support.

**Pull request closed without merging**
